name: Integration tests

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  run-integration-tests:
    name: "Run integration tests"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run didcomm tests
        env:
          WEBHOOK_URL: http://host.docker.internal:3000
        run: |
          ./docker/run.sh 1.39.1-101-228f07b
          npm i
          npm test
          ./docker/stop.sh
